jijiapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('', views.index, name='index' ),
    path('itemupload/<int:store_id>', views.itemupload, name='itemupload' ),
    # path('chat/<int:item_id>/', views.chat, name='chat' ),
    path('detail/<str:pk>/', views.detail, name='detail' ),
    path('chatdetail/<int:pk>/', views.chatdetail, name='chatdetail' ),
    path('inbox/', views.inbox, name='inbox' ),
    
    path('signup/', views.signup, name='signup' ),
    path('signout/', views.signout, name='signout' ),
    
    path('deletstore/<int:store_id>/', views.deletstore, name='deletstore' ),
    path('deleteitem/<int:item_id>/', views.deleteitem, name='deleteitem' ),
    path('edit_item/<int:item_id>/', views.edit_item, name='edit_item'),
    path('delete_inbox/<int:item_id>/', views.delete_inbox, name='delete_inbox' ),
    path('delete_con/<int:item_id>/', views.delete_con, name='delete_con' ),
    path('categories/<int:item_id>/', views.categories, name='categories' ),
    
    path('favorite/', views.favorite, name='favorite'),
    path('delete_fav/<int:item_id>/', views.delete_fav, name='delete_fav' ),
    path('contact/', views.contact, name='contact' ),
    # path('home/inbox/get_new_messages/', views.get_new_messages, name='get_new_messages'),
    path('reset_message_count/', views.reset_message_count, name='reset_message_count'),
    

]

jijiclone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from jijiapp.forms import LoginForm
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jijiapp.urls')),
    path('store/', include('jijistore.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='jijiapp/registration/login.html', authentication_form=LoginForm), name='login'),
    # path('accounts/', include('django.contrib.auth.urls')),
    # path('inbox/', include('jijiapp.routing')),
    
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(
        template_name='jijiapp/registration/password_reset.html'), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='jijiapp/registration/password_reset_done.html'), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='jijiapp/registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='jijiapp/registration/password_reset_complete.html'), name='password_reset_complete'),

]
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

jijistore/urls.py
from django.urls import path
from jijistore import views
from jijiapp.views import edit_item

app_name = 'jijistore'

urlpatterns = [
    path('storelist/', views.storelist, name='storelist' ),
    path('all_store/', views.all_store, name='all_store' ),
    path('enter_store/<str:store>/', views.enter_store, name='enter_store'),
    path('edit_store/<int:store_id>/', views.edit_store, name='edit_store'),
    # path('edit_item/<int:items_id>/', edit_item, name='edit_item'),
]

jijiapp/forms.py
from django.forms import ModelForm
from .models import Items, Images
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.forms.widgets import ClearableFileInput
from multiupload.fields import MultiFileField, MultiMediaField
from django.contrib.auth.forms import AuthenticationForm



# from multiupload.widgets import MultiClearableFileInput


from .models import ConversationMessage, Category



class ConversationMessageForm(forms.ModelForm):
    class Meta:
        model = ConversationMessage
        fields = ('content',)
        widgets = {
            'content': forms.Textarea(attrs={
                'class': 'w-10 rounded-xl border'
            })
        }
        


# class CategoryModelMultipleChoiceField(ModelMultipleChoiceField):
#     def label_from_instance(self, obj):
#         return obj.name

# class ItemsForm(forms.ModelForm):
#     category = CategoryModelMultipleChoiceField(queryset=Category.objects.all(), widget=forms.CheckboxSelectMultiple)

#     class Meta:
#         model = Items
#         exclude = ['user', 'store']


class ItemsForm(ModelForm):
    
    category = forms.ModelMultipleChoiceField(queryset=Category.objects.all(),
                                      widget=forms.SelectMultiple,)


    class Meta:
        model =Items
        # fields = ['title', 'price', 'phone', 'location','description', 'thumbnails', 'category']
        exclude = ['user', 'store']
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categorys =[(cat.id, cat.name) for cat in Category.objects.all()] 
        self.fields['category'].choices = [('', 'Select a Category')] + categorys   

class ImageForm(forms.ModelForm):
    image = MultiFileField(max_num=5, min_num=1)

    class Meta:
        model = Images
        fields = ['image',]

# class ImageForm(forms.ModelForm):
#     image = MultiFileField(widget=MultiClearableFileInput(attrs={'class': 'form-control'}))

#     class Meta:
#         model = Images
#         fields = ['image',]


# class ImageForm(ModelForm):
#     image = forms.ImageField(widget=ClearableFileInput(attrs={'class': 'form-control', "multiple":True}))

#     class Meta:
#         model = Images
#         fields = ['image',]
  
# class ImageForm(ModelForm):
#     image = forms.ImageField(widget =forms.FileInput(attrs  = {'class':'form-control',
#                 "multiple":True}))
    
#     class Meta:
#         model =Images
#         fields = ['image',]
        
# authentication

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': ''
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': ''
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': ''
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': ''
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': ''
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': ''
    }))
    
        
class CommentForm(forms.Form):
    detail = forms.CharField(label='Enter you View')
    
    

jijiapp/views.py
from django.shortcuts import render, redirect,get_object_or_404
from .models import *
from django.contrib.auth.models import User
from .forms import *
from django.contrib import messages
from django.http import Http404, JsonResponse
from django.db.models import Count, Q
from jijistore.views import enter_store
from django.contrib.auth import logout
from django.urls import reverse
from django.views.generic import ListView
from django.utils import timezone
from jijiapp.refractor import view, rate_item, category, get_message_count
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordResetDoneView
from django.contrib.auth.forms import PasswordResetForm
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from django.views.decorators.http import require_GET

from time import sleep


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('login')
    else:
        form = SignupForm()

    return render(request, 'jijiapp/registration/signup.html', {
        'form': form
    })
    
def signout(request):
    logout(request)
    messages.info(request, 'You just logged out, login again!')
    return redirect('login')
# end of uth
@login_required
def contact(request):
    contacts =Contact.objects.all()
    if request.method =='POST':
        name = request.POST['name']
        email = request.POST['email']
        message = request.POST['message']
        
        contact_info = Contact.objects.create(name = name, email=email, message= message)
        messages.info(request, f'thank you {name} for contacting us. We will get back to you soon!')
        return redirect('contact')
    context = {
        'contacts':contacts,
    }
    return render(request, 'jijiapp/contact.html', context)
@login_required
def inbox(request):
    conversations = Conversation.objects.filter(members=request.user)

    count = 0
    for conversation in conversations:
        conversation_counts = ConversationCount.objects.filter(conversation=conversation)
        for conversation_count in conversation_counts:
            count += conversation_count.message_count

    
    if request.method == 'POST' and 'reset_message_count' in request.POST:
        ConversationCount.objects.filter(conversation__members=request.user).update(message_count=0)
        return redirect('inbox')
    
    context = {
        'conversations': conversations,
        'count': count,
    }
    
    return render(request, 'jijiapp/inbox.html', context)

def reset_message_count(request):
    if request.method == 'POST':
        ConversationCount.objects.filter(conversation__members=request.user).update(message_count=0)
        return redirect('inbox')
    
@login_required  
def index(request):
    
    img = HomeImage.objects.all()
    homeimage = img.first()
    user = request.user
    
    conversations = Conversation.objects.filter(members=request.user)
    

    count = 0
    for conversation in conversations:
        conversation_counts = ConversationCount.objects.filter(conversation=conversation)
        for conversation_count in conversation_counts:
            count += conversation_count.message_count

    if request.method == 'POST' and 'reset_message_count' in request.POST:
        ConversationCount.objects.filter(conversation__members=request.user).update(message_count=0)
        return redirect('inbox')
    
    
    if user.is_authenticated:
         
            # hiding favorite when user added
        if request.method == 'POST' and 'favorite' in request.POST:
            favorite_id = request.POST.get('favorite_id')
            favorite_item = Items.objects.get(id=favorite_id)
            Favorite.objects.create(user=request.user, item=favorite_item)
        
        # Get favorite items
        fav = Items.objects.filter(favorite__user=user)
        # end
        item = Items.objects.all()
    
        # search logic
        name = request.GET.get('search')
        
        item_category = item.filter(Q(category__name__icontains=name) 
                                | Q(description__icontains=name) 
                                | Q(title__icontains=name) 
                                | Q(title__istartswith=name) 
                                | Q(category__name__istartswith=name)) if name else None
        
        
            # return JsonResponse({'count': count})
        viewed_items = Items.objects.filter(useritemview__user=user).order_by('-useritemview__view_date')[:3]
    else:
        
        item = Items.objects.all()
        
        # search logic
        name = request.GET.get('search')
        
        item_category = item.filter(Q(category__name__icontains=name) 
                                | Q(description__icontains=name) 
                                | Q(title__icontains=name) 
                                | Q(title__istartswith=name) 
                                | Q(category__name__istartswith=name))if name else None#if name else messages.info(request, 'no item with name %s' %(name))
        # if name ==None:
        #     messages.info(request, 'Dont leave blank')
            
    
    
        viewed_items = None
        
        fav =None
    category = Category.objects.all()
    context = {
        'user': user,
        'category':category,
        'all_item': item,
        'count': count,
        'name': name,
        'viewed_items': viewed_items,
        'item_category': item_category,
        'homeimage':homeimage,
        'favs': fav,
    }
    
    item = view(request)
    if item:
        return redirect('detail', pk=item.id)
   
    return render(request, 'jijiapp/index.html', context)

def categories(request, item_id):
    
    
    catego =category(request, item_id)   
    context = {
        'category': catego,
    }
    return render(request, 'jijiapp/categories.html', context)

    
    
@login_required
def detail(request, pk):
    img = HomeImage.objects.all()
    homeimage = img.first()
    user = request.user
    # item =Items.objects.all()
    # item_url = reverse('chat', args=[pk])
    chat_url = reverse('chatdetail', args=[pk])
    
    try:
        items = Items.objects.get(pk = pk)
     
    except Items.DoesNotExist:
        items = Items.objects.filter(title = pk)
    store_url = items.store.id
    store_routing = reverse('jijistore:enter_store', args = [store_url])
    
    # category
    # cat =items.category.all()
    
    # category = Items.objects.filter(category__in=cat).exclude(pk=items.pk)
    catego =category(request, pk)
   
   
    conversations = Conversation.objects.filter(members=request.user)
    
    count = 0
    for conversation in conversations:
        conversation_counts = ConversationCount.objects.filter(conversation=conversation)
        for conversation_count in conversation_counts:
            count += conversation_count.message_count

    

    if request.method == 'POST' and 'reset_message_count' in request.POST:
        ConversationCount.objects.filter(conversation__members=request.user).update(message_count=0)
        return redirect('inbox')
    
    
    if user.is_authenticated:
         
            # hiding favorite when user added
        if request.method == 'POST' and 'favorite' in request.POST:
            favorite_id = request.POST.get('favorite_id')
            favorite_item = Items.objects.get(id=favorite_id)
            Favorite.objects.create(user=request.user, item=favorite_item)
    
    # feedback section
    comments = Comment.objects.filter(item=items)
   

    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            detail = form.cleaned_data['detail']
            comment = Comment.objects.create(content = detail, user=user, item=items )
            
            return JsonResponse({'detail': comment.content, 
                                 'user': comment.user.username, 'post_date': comment.post_date.strftime("%Y-%m-%d %H:%M:%S")})
            # # messages.info(request, 'Thank you for the feed back')
            # return redirect('detail', pk=pk)
    else:
        form = CommentForm()
        
    # search section
   
    name = request.GET.get('search')
    item_category = item.filter(Q(category__name__icontains=name) 
                            | Q(description__icontains=name) 
                            | Q(title__icontains=name) 
                            | Q(title__istartswith=name) 
                            | Q(category__name__istartswith=name))if name else None
    
    viewed_items = Items.objects.filter(useritemview__user=user).order_by('-useritemview__view_date')[:3]
    
    # rating
    rate_item(request, pk)
    
    context = {
        
        'detail_item':items,
        'comments': comments,
        'form': form,
        # 'all_item':item,
        'user':user,
        'count':count,
        # 'item_url':item_url,
        'chat_url':chat_url,
        'store_routing':store_routing,
        'name':name,
        'item_category':item_category,
        'viewed_items':viewed_items,
        'homeimage':homeimage,
        'category':catego,
    }
    
    item = view(request)
    if item:
        return redirect('detail', pk=item.id)
    return render(request, 'jijiapp/jijidetail.html', context)


@login_required
def itemupload(request, store_id):
    user = request.user
    items = Items.objects.filter(user=request.user)[:4]
    item_url = reverse('itemupload', args=[store_id])
    i = Items.objects.filter(user=request.user)
    categories = Category.objects.filter(name__in=i.values('category'))
    
    if store_id:
        store = get_object_or_404(Store, pk=store_id)
    else:
        store = None

    if request.method == 'POST':
        itemsform = ItemsForm(request.POST, request.FILES)
        imageforms = ImageForm(request.POST, request.FILES)

jijiapp/templates/jijiapp/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Market Place</title>

   <!-- css -->
   
    
    <!-- font  awesome   -->

    <https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.1/css/fontawesome.min.css>
    <!-- font awesome html -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.1/css/fontawesome.min.css" integrity="sha384-QYIZto+st3yW+o8+5OHfT6S482Zsvz2WfOzpFSXMF9zqeLcFV0/wlZpMtyFcZALm" crossorigin="anonymous">

    <!-- font awesome plug -->
    <link(rel="stylesheet", href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.1/css/fontawesome.min.css", integrity="sha384-QYIZto+st3yW+o8+5OHfT6S482Zsvz2WfOzpFSXMF9zqeLcFV0/wlZpMtyFcZALm", crossorigin="anonymous")>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> 

    <link rel='stylesheet' type='text/css' media='screen' href="{% static 'jijiapp/css/style.css' %}"> 
   
    <!-- bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- <script src="{% static 'script.js' %}"></script> -->
 <style>
  /* for categorys controlling the height and the layout of the images */

.rowheight {
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
}

.colheight {
  display: flex;
  flex-direction: column;
  justify-content: center;
}

.card {
  height: 100%;
}

.card-img-top {
  
  object-fit: contain;
  border-radius: 5px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.card-img-top:hover {
  transform: scale(1.05);
  transition: transform 0.3s ease;
}
/* end */
 </style>   

<script>
$(document).ready(function() {
  // Get the CSRF token from the cookie
  function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
      var cookies = document.cookie.split(';');
      for (var i = 0; i < cookies.length; i++) {
        var cookie = cookies[i].trim();
        // Does this cookie string begin with the name we want?
        if (cookie.substring(0, name.length + 1) === (name + '=')) {
          cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
          break;
        }
      }
    }
    return cookieValue;
  }

  // Set up AJAX to include CSRF token in headers
  function csrfSafeMethod(method) {
    // These HTTP methods do not require CSRF protection
    return /^(GET|HEAD|OPTIONS|TRACE)$/.test(method);
  }

  var csrftoken = getCookie('csrftoken');
  $.ajaxSetup({
    beforeSend: function(xhr, settings) {
      if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
        xhr.setRequestHeader('X-CSRFToken', csrftoken);
      }
    }
  });
});

</script> 
    
</head>
<body>
 
    
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #ffffff;">
    <div class="container mb-5">
      <a class="navbar-brand" href="{% url 'index' %}" style="color: #fd7e14;"><strong>Welcome to Market Place</strong></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'index' %}" style="color: #343a40;"><i class="fa fa-home"></i>Home</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'favorite' %}" style="color: #343a40;">Favorite</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'jijistore:all_store' %}" style="color: #343a40;">Enter Store</a>
          </li>
          
          <li class="nav-item">
            <form class="nav-link reset-message-count" method="post" action="{% url 'reset_message_count' %}">
              {% csrf_token %}
              <button type="submit" style="background: none; border: none; color: #343a40; text-decoration: underline; cursor: pointer;">
                Inbox <span class="badge bg-danger message-count" id="message-count">{{ count }}</span>
              </button>
            </form>
          </li>
          
          
          
        
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contact' %}" style="color: #343a40;">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#" style="color: #343a40;">| Helo, {{user.username}} </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'signout' %}" style="color: #343a40;">| Logout </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contact' %}" style="color: #343a40;">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}" style="color: #343a40;">| <i class="fa fa-key"></i>login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link mx-2" href="{% url 'signup' %}" style="color: #fd7e14;">| Signup</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  

<div class="container">
    
    {% block content %}
    {% endblock %}
</div>




<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
<script src="{% static 'js/script.js' %}"></script>




    
</body>
</html>

jijiapp/templates/jijiapp/base/footer.html
<footer class="footer bg-dark text-light py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <h5>About Us</h5>
          <p>Welcome to Wilf Market Place, where connecting buyers and sellers is our passion. 
            We believe in the power of a vibrant online marketplace to transform the way 
            people discover, buy, and sell products.</p>
        </div>
        <div class="col-md-4">
          <h5>Contact Us</h5>
          <ul class="list-unstyled">
            <li>Email: mathiaswilfred7@yahoo.com</li>
            <li>Phone: +2348134622388</li>
            <li>Address: Dafa, Kwali Area Council FCT, Abuja Nigeria</li>
          </ul>
        </div>
        <div class="col-md-4">
          <h5>Follow Us</h5>
          <ul class="list-inline">
            <li class="list-inline-item"><a href="#"><i class="fa fa-facebook-f"></i></a></li>
            <li class="list-inline-item"><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li class="list-inline-item"><a href="#"><i class="fa fa-instagram"></i></a></li>
          </ul>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-md-6">
          <p>&copy; 2023 wilf Market Place. All rights reserved.</p>
        </div>
        <div class="col-md-6 text-md-end">
          <ul class="list-inline">
            <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
            <li class="list-inline-item"><a href="#">Terms of Service</a></li>
            <li class="list-inline-item"><a href="#">Cookie Policy</a></li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
  

jijiapp/templates/jijiapp/base/homebase.html
<div class="container container-fluid mb-5">
  <div class="row rowwidth pt-5 bg-dark">
    {% for item in all_item %}
    <div class="col-lg-4 col-md-4 col-sm-6 mb-5 colheight">
      <div class="card bg-light card-style">
        <a href="{% url 'detail' item.id %}" class="card-link text-decoration-none">
          <img src="{{ item.thumbnails.url }}" alt="First Image" class="card-img-top img-fluid mx-auto align-items-stretch">
        </a>
        <div class="card-body">
          <h5 class="card-title">{{ item.title }}</h5>
          <hr class="star-light">
          <p class="card-text">Price: <strike>N</strike>{{ item.price }}</p>
          <hr>
          {% if user.is_authenticated %}
          <form id="form-{{ item.id }}" method="post">
            {% csrf_token %}
            <input type="hidden" name="item_id" value="{{ item.id }}">
            <button type="submit" class="btn btn-primary btn-block col-sm-12 col-md-12 col-lg-12">
              Save this item
            </button>
          </form>
          {% else %}
          <a href="{% url 'login' %}" class="btn btn-success btn-sm btn-block" style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">Login to buy this item</a>
          {% endif %}
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

jijiapp/templates/jijiapp/base/storebase.html
<div class="card">
    <div class="loaction text-center">
        <p class="lead">Find Store</p>
    </div>

    <form action="." method="get" class="d-flex justify-content-center">
        <div class="form-outline col-sm-6 col-md-4">
            <div class="label">
                <input id="search-input" type="search" name="search" class="form-control"
                        placeholder="Search" style="height: 50px;"/>
                <label class="form-label" for="form1"></label>
            </div>
        </div>
        <button id="search-button" class="btn btn-primary" style="height: 50px;">
            <i class="fa fa-search"></i>
        </button>
    </form>

    {% if search_store %}
    <div class="row rowwidth pt-5 bg-light mb-5"> 
    {% for store in search_store %}
    <div class="col-sm-4 col-md-4 col-lg-3 card-style3 mb-4 mx-auto">
        <div class="card card-style h-100" style="background-color: rgb(196, 223, 223)">
            <div class="card-image-top">
                <div class="container">
                    <div class="row pt-2">
                        <div class="col-2">
                            <img src="{{ store.logo.url }}" alt="first image" class="thumbnails" style="width: 50px; height: 50px;">
                        </div>
                        <div class="col-6 mx-auto bg-dark text-white p-2 text-center lead">
                            <p class="card-title text-white" style="font-size: 0.9rem;">{{ store.name }}</p>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <hr>
                    <p class="card-text card1">{{ store.discription }}</p>
                    <hr>
                    <p class="card-text">Location: {{ store.location }}</p>
                    <small class="card-footer text-danger">{{ store.create_date | date }} | {{ store.author }}</small>
                    <hr>
                    <div class="row">
                        {% if user != store.author %}
                        <div class="col-12 text-center mb-3">
                            <a href="{% url 'jijistore:enter_store' store.id %}" class="btn btn-success">Enter Store</a>
                        </div>
                        {% else %}
                        <div class="col-6 text-center mb-3">
                            <a href="{% url 'itemupload' store.id %}" class="btn btn-success">Add Item</a>
                        </div>
                        <div class="col-6 text-center mb-3">
                            <a href="{% url 'jijistore:enter_store' store.id %}" class="btn btn-success">Enter</a>
                        </div>
                        <div class="col-6 text-center mb-3">
                            <a href="{% url 'deletstore' store.id %}" class="btn btn-success bg-danger">Delete</a>
                        </div>
                        <div class="col-6 text-center mb-3">
                            <a href="{% url 'jijistore:edit_store' store.id %}" class="btn btn-success bg-success">Edit</a>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    </div>
    {% elif search_store == None %}
        <p class="text-center text-danger">
            Search for Store here!! 
            
        </p>
    {% else %}
        <p class="text-center text-danger">
            
            No Store with name {{ name }}
        </p>
    {% endif %}
</div>