jijiapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('', views.index, name='index' ),
    path('itemupload/<int:store_id>', views.itemupload, name='itemupload' ),
    # path('chat/<int:item_id>/', views.chat, name='chat' ),
    path('detail/<str:pk>/', views.detail, name='detail' ),
    path('chatdetail/<int:pk>/', views.chatdetail, name='chatdetail' ),
    path('inbox/', views.inbox, name='inbox' ),
    
    path('signup/', views.signup, name='signup' ),
    path('signout/', views.signout, name='signout' ),
    
    path('deletstore/<int:store_id>/', views.deletstore, name='deletstore' ),
    path('deleteitem/<int:item_id>/', views.deleteitem, name='deleteitem' ),
    path('edit_item/<int:item_id>/', views.edit_item, name='edit_item'),
    path('delete_inbox/<int:item_id>/', views.delete_inbox, name='delete_inbox' ),
    path('delete_con/<int:item_id>/', views.delete_con, name='delete_con' ),
    path('categories/<int:item_id>/', views.categories, name='categories' ),
    
    path('favorite/', views.favorite, name='favorite'),
    path('delete_fav/<int:item_id>/', views.delete_fav, name='delete_fav' ),
    path('contact/', views.contact, name='contact' ),
    # path('home/inbox/get_new_messages/', views.get_new_messages, name='get_new_messages'),
    path('reset_message_count/', views.reset_message_count, name='reset_message_count'),
    

]

jijiclone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from jijiapp.forms import LoginForm
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jijiapp.urls')),
    path('store/', include('jijistore.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='jijiapp/registration/login.html', authentication_form=LoginForm), name='login'),
    # path('accounts/', include('django.contrib.auth.urls')),
    # path('inbox/', include('jijiapp.routing')),
    
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(
        template_name='jijiapp/registration/password_reset.html'), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='jijiapp/registration/password_reset_done.html'), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='jijiapp/registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='jijiapp/registration/password_reset_complete.html'), name='password_reset_complete'),

]
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

jijistore/urls.py
from django.urls import path
from jijistore import views
from jijiapp.views import edit_item

app_name = 'jijistore'

urlpatterns = [
    path('storelist/', views.storelist, name='storelist' ),
    path('all_store/', views.all_store, name='all_store' ),
    path('enter_store/<str:store>/', views.enter_store, name='enter_store'),
    path('edit_store/<int:store_id>/', views.edit_store, name='edit_store'),
    # path('edit_item/<int:items_id>/', edit_item, name='edit_item'),
]

jijistore/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

# class Store(models.Model):
#     name = models.SlugField(unique =True, max_length=50)
#     author = models.ForeignKey(User, on_delete=models.CASCADE, blank=False)
#     create_date = models.DateTimeField(auto_now_add=True, null=True)
#     discription=models.CharField(max_length=5000, null=True, blank=True)
#     location =models.CharField(max_length=5000, null=True, blank=True)
#     logo =models.ImageField(upload_to='logos/', default = '')
#     def __str__(self):
#         return '%s' % (self.name)
    
#     class Meta:
#         ordering = ['-name']
#         verbose_name_plural = 'Store'
    
class Items(models.Model):
    title = models.CharField(max_length=50, null=True, blank=True)
    image = models.ImageField(upload_to='store/')
    # store = models.ForeignKey(Store, on_delete=models.CASCADE, blank=False)
    date_uploaded=models.DateTimeField(auto_now_add=True)
    price =models.DateTimeField(auto_now_add=True)
    discription=models.CharField(max_length=5000, null=True, blank=True)
    
    def __str__(self):
        return '%s' % (self.title)
    
    class Meta:
        ordering = ['-title']
        verbose_name_plural = 'Items'
    

jijistore/forms.py
from django import forms

class storeForm(forms.Form):
    name = forms.CharField(label='Your Store name')
    discription = forms.CharField(label='description')
    # create_date= forms.DateField(widget = forms.DateInput)
    location = forms.CharField(label='location')
    
    logo = forms.ImageField()

jijistore/views.py
from django.shortcuts import render, redirect, get_object_or_404
from jijiapp.models import Items, Store, Images
from jijistore.forms import storeForm
from django.contrib import messages
from django.urls import reverse
from django.db.models import Count, Q
from django.contrib.auth.decorators import login_required

# Create your views here.


# this views create store
@login_required
def storelist(request):
    user = request.user
    created_by_you = Store.objects.filter(author =user)
    if request.method == 'POST':
        form = storeForm(request.POST, request.FILES)
        if form.is_valid():
            name = form.cleaned_data.get('name')
            description = form.cleaned_data.get('discription')
            # date_uploaded = form.cleaned_data.get('create_date')
            location = form.cleaned_data.get('location')
            logo = form.cleaned_data.get('logo')
            
            if Store.objects.filter(name = name).exists():
                messages.error(request, f'{name} Store already exist')
                return redirect('jijistore:storelist')
            
            store= Store.objects.create(author=user, name = name, discription=description,
                    location=location,logo =logo)
           
            
            messages.success(request, f'The Store with name {name} created successful')
            return redirect('jijistore:storelist')
        messages.error(request, f'Invalid data')
        return redirect('jijistore:storelist')
    form = storeForm()
    context = {
        'form':form,
        'created_by_you':created_by_you,
    }
    return render(request, 'jijistore/store.html', context)
@login_required
def all_store(request):
    store = Store.objects.all()
    
    name = request.GET.get('search')
        
    search_store= store.filter(Q(name__icontains=name) 
                            | Q(author__username__icontains=name) 
                            | Q(discription__icontains=name)) if name else None
    
    
    context = {
        'name':name,
        'stores':store,
        'search_store':search_store,
    }
    return render(request, 'jijistore/all_store.html', context)

@login_required
def enter_store(request, store):
    
    try:
        stor = Store.objects.get(id=store)
        all_items = stor.items_set.all()
    except Store.DoesNotExist:
        all_items = None
        stor =None
        # all_items = stor.items_set.all()

    context = {
        'details':stor,
        'all_item':all_items,
    }
    return render(request, 'jijistore/store_detail.html', context)
@login_required
def edit_store(request, store_id):
    
    store = get_object_or_404(Store, name=store_id)
    if request.method == 'POST':
        form = storeForm(request.POST, request.FILES, 
                         initial={
                        'name': store.name,
                        'discription': store.discription,
                        'location': store.location,
                        'logo': store.logo,})
        if form.is_valid():
            store.name = form.cleaned_data.get('name')
            store.discription = form.cleaned_data.get('discription')
            store.location = form.cleaned_data.get('location')
            store.logo = form.cleaned_data.get('logo')
            
            store.save()
            messages.success(request, 'Store updated')
            return redirect('jijistore:all_store')
        messages.error(request, 'Invalid input')
        reverse('edit_store', args = [store_id])
        
    # initial_values = {
    #         'name': store.name,
    #         'discription': store.discription,
    #         'location': store.location,
    #         'logo': store.logo,
    #     }
    form = storeForm(initial={
            'name': store.name,
            'discription': store.discription,
            'location': store.location,
            'logo': store.logo,
        })
    context = {
        'form':form,
        'store':store,
    }
    return render(request, 'jijistore/store_update.html', context)
            
        
    

jijistore/templates/jijistore/all_store.html
{% extends 'jijiapp/base/base.html' %}
{% load static %}

{% block title %} All Store {% endblock %}


{% block content %}

<div class="mx-5 px-5 col-md-5 col-sm-12 mx-auto bg-info ">
    <div class="text-danger text-center">
        {% for message in messages %}
        <span>{{ message }}</span>
        {% endfor %}
    </div>
</div>
<div class="container mb-5">
    <div class="col-sm-8 col-md-6 col-lg-4 mx-auto">
        <div class="text-center py-4 rounded-lg" style="background-color: #ff7f50;">
            <h2 class="h4 font-weight-bold text-white">Enter a Store</h2>
            <p class="text-white">Discover unique products and explore amazing stores</p>
            <a href="{% url 'jijistore:storelist' %}" class="btn btn-light btn-lg mt-3">Create Store</a>
        </div>
    </div>
</div>




<div class="row pt-5 bg-dark">
    <div class="container container-fluid">
        <div class="text-center my-4 bg-primary rounded p-4">
            <h3 class="text-white mb-3">Add Store</h3>
            <a href="{% url 'jijistore:storelist' %}" class="btn btn-light btn-lg px-4 py-2">
                <i class="fa fa-plus"></i> Add New Store
            </a>
            <p class="text-white mt-3">Expand your business and reach more customers.</p>
        </div>
    </div>

    {% include 'jijiapp/base/storebase.html' %}

    {% for store in stores %}
    <div class="col-sm-4 col-md-4 col-lg-3 card-style3 mb-4 pt-3">
        <div class="card card-style h-100" style="background-color: rgb(196, 223, 223)">
            <div class="card-image-top">
                <div class="container">
                    <div class="row pt-2">
                        <div class="col-2">
                            <img src="{{ store.logo.url }}" alt="first image" class="thumbnails" style="width: 50px; height: 50px;">
                        </div>
                        <div class="col-6 mx-auto bg-dark text-white p-2 text-center lead">
                            <p class="card-title text-white" style="font-size: 0.9rem;">{{ store.name }}</p>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <hr>
                    <p class="card-text text-white bg-dark">{{ store.discription }}</p>
                    <hr>
                    <p class="card-text">Location: {{ store.location }}</p>
                    <small class="card-footer text-danger">{{ store.create_date | date }} | {{ store.author }}</small>
                    <hr>
                    <div class="row">
                        {% if user != store.author %}
                        <div class="col-12 text-center mb-3">
                            <a href="{% url 'jijistore:enter_store' store.id %}" class="btn btn-success">Enter Store</a>
                        </div>
                        {% else %}
                        <div class="col-6 text-center mb-3">
                            <a href="{% url 'itemupload' store.id %}" class="btn btn-success">Add Item</a>
                        </div>
                        <div class="col-6 text-center mb-3">
                            <a href="{% url 'jijistore:enter_store' store.id %}" class="btn btn-success">Enter</a>
                        </div>
                        <div class="col-6 text-center mb-3">
                            <a href="{% url 'deletstore' store.id %}" class="btn btn-success bg-danger">Delete</a>
                        </div>
                        <div class="col-6 text-center mb-3">
                            <a href="{% url 'jijistore:edit_store' store.id %}" class="btn btn-success bg-success">Edit</a>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>



{% endblock %}

jijistore/templates/jijistore/store.html
{% extends 'jijiapp/base/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Upload Item {% endblock %}


{% block content %}
<div class="container mb-3" style="font:bold;">
    <div class="col-5 bg-dark mx-auto text-white">
        <div class="text-center pt-5 pb-3">
            <h2 class="lead text-bold" style="font-size:2rem; font-weight: bold;">Create Store</h2>
        </div>
    </div>

</div>

<div class="mx-5 px-5 col-md-5 mx-auto bg-dark ">
    <div class="text-danger">
        {% for message in messages %}
        <span>{{ message }}</span>
        {% endfor %}
    </div>
<form action="" method="post", enctype="multipart/form-data">
    
        {% csrf_token %}
        
        <div class = "row mb-3">
            <label class="col-md-5 col-form-label">{{ form.label }}</label>
            <div class="col-sm-5 form-control ">
                {{ form.name|as_crispy_field }}
            </div>
            {% for field in form %}
            {{ field.name.errors }}
            {% endfor %}
        </div>
        <div class = "row mb-3">
            <label class="col-md-2 col-form-label">{{ form.label }}</label>
            <div class="col-sm-10 form-control">
                {{ form.discription|as_crispy_field }}
            </div>
            {% for field in form %}
            {{ field.discription.errors }}
            {% endfor %}
            
        </div> 
        <div class = "row mb-3">
            <label class="col-md-2 col-form-label">{{ form.label }}</label>
            <div class="col-sm-10 form-control">
                {{ form.location|as_crispy_field }}
            </div>
            {% for field in form %}
            {{ field.location.errors }}
            {% endfor %}
        </div> 
        
        <div class = "row mb-3">
            <label class="col-md-2 col-form-label">{{ form.label }}</label>
            <div class="col-sm-10 form-control">
                {{ form.logo |as_crispy_field}}
            </div>
            {% for field in form %}
            {{ field.logo.errors }}
            {% endfor %}
        </div> 
        
      
       <button class="btn btn-secondary mb-5">Create Store</button>
        

    </form>

</div>
<div class="col-md-8 bg-light" style ="justify-content: center;">
    <div class="text-center pt-5 pb-3">
        <h2>Stores you created</h2>
    </div>
</div>

<div class="row rowwidth pt-5 bg-dark">
    {% for store in created_by_you %}
    <div class="col-sm-6 col-md-4 col-lg-4 card-style3 mb-4">
        <div class="card" style="background-color:rgb(196, 223, 223)">
            <div class="card-image-top">
                <div class="container">
                    <div class="row pt-2">
                        <div class="col-2">
                            <img src="{{ store.logo.url }}" alt="first image" class="thumbnails" style="width:50px; height:50px;">
                        </div>
                        <div class="col-6 mx-auto bg-dark text-white p-2 text-center lead">    
                            <p class="card-title">{{ store.name }}</p>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <hr>
                    <p class="card-text card1">{{ store.discription }}</p>
                    <hr>
                    <p class="card-text">Location:{{ store.location}}</p>
                    <small class="card-footer text-danger">{{ store.create_date |date  }} | {{ store.author }}</small>
                    <hr>
                    <div class="row ">
                        {% if user != store.author %}
                        <div class="col-12 text-center mb-3">
                            <a href="{% url 'jijistore:enter_store' store.id %}" class="btn btn-success">Enter store</a>
                        </div> 
                        {% else %}  
                        <div class="col-6 text-center mb-3">
                            <a href="{% url 'itemupload' store.id %}" class= "btn btn-success">Add Item</a>
                        </div>
                        <div class="col-6 text-center mb-3">
                            <a href="{% url 'jijistore:enter_store' store.id %}" class="btn btn-success">Enter</a>
                        </div>
                        <div class="col-6 text-center mb-3">
                            <a href="{% url 'deletstore' store.id %}" class="btn btn-success bg-danger">Delete</a>
                        </div>
                        <div class="col-6 text-center mb-3">
                            <a href="{% url 'jijistore:edit_store' store.id %}" class="btn btn-success bg-success">Edit</a>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
     


{% endblock %}

jijistore/templates/jijistore/store_detail.html
{% extends 'jijiapp/base/base.html' %}
{% load static %}
{% block title %} Welcome to Jiji Clone {% endblock %}

{% block content %}
<div class="mx-5 px-5 col-md-5 mx-auto bg-info">
    
    <div class="text-danger text-center">
        {% for message in messages %}
        <span>{{ message }}</span>
        {% endfor %}
        
    </div>
    
</div>
<div class="container my-4">
    <div class="col-sm-8 col-md-6 col-lg-4 mx-auto">
        <div class="text-center py-4 rounded-lg" style="background-color: #ff7f50;">
            <h2 class="h4 font-weight-bold text-white">{{ details.name }}</h2>
            <p class="text-white">Fine all items you need here</p>
            <a href="{% url 'jijistore:all_store' %}" class="btn btn-light btn-lg mt-3">Back to store</a>
        </div>
    </div>
</div>
{% if all_item %}
{% include 'jijiapp/base/homebase.html' %}
{% else %}
<p class="text-center text-danger">
    No Item in this store yet.!!
</p>
{% endif %}
</div>
{% endblock %}

jijistore/templates/jijistore/store_update.html
{% extends 'jijiapp/base/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Upload Item {% endblock %}


{% block content %}
<div class="container mb-3" style="font:bold;">
    <div class="col-5 bg-dark mx-auto text-white">
        <div class="text-center pt-5 pb-3">
            <h2 class="lead text-bold" style="font-size:2rem; font-weight: bold;">Update Store {{ store.name }}</h2>
        </div>
    </div>

</div>

<div class="mx-5 px-5 col-md-5 mx-auto bg-dark ">
    <div class="text-danger">
        {% for message in messages %}
        <span>{{ message }}</span>
        {% endfor %}
    </div>
<form action="." method="post", enctype="multipart/form-data">
    
        {% csrf_token %}
        
        <div class = "row mb-3">
            <label class="col-md-5 col-form-label">{{ form.label }}</label>
            <div class="col-sm-5 form-control ">
                {{ form.name|as_crispy_field }}
            </div>
            {% for field in form %}
            {{ field.name.errors }}
            {% endfor %}
        </div>
        <div class = "row mb-3">
            <label class="col-md-2 col-form-label">{{ form.label }}</label>
            <div class="col-sm-10 form-control">
                {{ form.discription|as_crispy_field }}
            </div>
            {% for field in form %}
            {{ field.discription.errors }}
            {% endfor %}
            
        </div> 
        <div class = "row mb-3">
            <label class="col-md-2 col-form-label">{{ form.label }}</label>
            <div class="col-sm-10 form-control">
                {{ form.location|as_crispy_field }}
            </div>
            {% for field in form %}
            {{ field.location.errors }}
            {% endfor %}
        </div> 
        
        <div class = "row mb-3">
            <label class="col-md-2 col-form-label">{{ form.label }}</label>
            <div class="col-sm-10 form-control">
                {{ form.logo |as_crispy_field}}
            </div>
            {% for field in form %}
            {{ field.logo.errors }}
            {% endfor %}
        </div> 
        
      
       <button class="btn btn-secondary mb-5">Create Store</button>
        

    </form>

</div>
<div class="col-md-8 bg-light" style ="justify-content: center;">
    <div class="text-center pt-5 pb-3">
        <h2>Stores you created</h2>
    </div>
</div>
<div class="row rowwidth pt-5 bg-dark">

{% for store in created_by_you %}
<div class="col-md-2 col-sm-4 col-lg-2 card-style">
    <div class="card" style="background-color:rgb(196, 223, 223)">
    <div class="card-image-top">
        <div class="container">
            <div class="row pt-2">
                <div class="col-2">
                    <img src="{{ store.logo.url }}" alt="first image" class="thumbnails" style="width:50px; height:50px;">
                </div>
                
                <div class="col-6 mx-auto bg-dark text-white p-2 text-center lead">    
                    <p class="card-title">{{ store.name }}</p>
                </div>
            </div>

        </div>
        
        <div class="card-body">
        
        <hr>
        
        <p class="card-text card1">{{ store.discription }}</p>
        
        <hr>
        <p class="card-text">Location:{{ store.location}}</p>
        
        <small class="card-footer text-danger">{{ store.create_date |date  }} | {{ store.author }}</small>
        <hr>
        <a href="{% url 'jijistore:enter_store' store.id %}" class="btn btn-success">Enter store</a>
        </div>
        
    </div>
    </div>
    
</div>

{% endfor %}
</div>
    


{% endblock %}

jijistore/templates/jijistore/storelist.html
{% extends 'jijiapp/base/base.html' %}
{% load static %}
{% block title %} Welcome to Jiji Clone {% endblock %}

{% block content %}


<div class="">
  
    
    <div class="col-sm-4 col-md-4 mx-auto">
      <img src="{% static 'images/speaker.jfif' %}" alt="images/jiji man image.png">
    </div>
  
</div>
  
<div class="card">
  
  
  <div class="loaction text-center">
    <p class="lead">Fine everything you want all in <strong><i class="fa fa-map"></i> Nigeria </strong></p>
  </div>

  
  
    <div class="input-group">
  
      <div class="form-outline ">
        <div class="label">
          <input id="search-input" type="search" id="form1" class="form-control" placeholder="Search" style="height: 50px; width: 500px;"/>
          <label class="form-label" for="form1"></label>
        </div>
      </div>
      <button id="search-button" type="button" class=" btn btn-primary " style="height: 50px;">
        <i class="fa fa-search"></i>
      </button>
    
       
    </div>
  
{% block name %}
{% endblock %}
<div class="row rowwidth pt-5 bg-dark">
  
  {% for item in items %}
  <div class="col-md-2 col-sm-4 col-lg-2 card-style">
    <div class="card" style="background-color:rgb(196, 223, 223)">
      <div class="card-image-top">
        
        <img src="{{ item.thumbnails.url }}" alt="first image" class="image1 thumbnails  w-100" >
        
        <div class="card-body">
          <p class="card-title">{{ item.title }}</p>
          <hr>
         
          <p class="card-text card1">{{ item.description }} | {{ count.count }} pics</p>
          
          <hr>
          <p class="card-text">Price: <strike>N</strike>{{ item.price }}</p>
          
          <small class="card-footer text-danger">{{ item.post_date |date  }} | {{ item.user }}</small>
          <hr>
          <a href="{% url 'detail' item.id %}" class="btn btn-success">View details</a>
        </div>
        
      </div>
    </div>
    
  </div>

  {% endfor %}
</div>


</div>

{% endblock %}