jijiapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('', views.index, name='index' ),
    path('itemupload/<int:store_id>', views.itemupload, name='itemupload' ),
    # path('chat/<int:item_id>/', views.chat, name='chat' ),
    path('detail/<str:pk>/', views.detail, name='detail' ),
    path('chatdetail/<int:pk>/', views.chatdetail, name='chatdetail' ),
    path('inbox/', views.inbox, name='inbox' ),
    
    path('signup/', views.signup, name='signup' ),
    path('signout/', views.signout, name='signout' ),
    
    path('deletstore/<int:store_id>/', views.deletstore, name='deletstore' ),
    path('deleteitem/<int:item_id>/', views.deleteitem, name='deleteitem' ),
    path('edit_item/<int:item_id>/', views.edit_item, name='edit_item'),
    path('delete_inbox/<int:item_id>/', views.delete_inbox, name='delete_inbox' ),
    path('delete_con/<int:item_id>/', views.delete_con, name='delete_con' ),
    path('categories/<int:item_id>/', views.categories, name='categories' ),
    
    path('favorite/', views.favorite, name='favorite'),
    path('delete_fav/<int:item_id>/', views.delete_fav, name='delete_fav' ),
    path('contact/', views.contact, name='contact' ),
    # path('home/inbox/get_new_messages/', views.get_new_messages, name='get_new_messages'),
    path('reset_message_count/', views.reset_message_count, name='reset_message_count'),
    

]

jijiclone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from jijiapp.forms import LoginForm
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jijiapp.urls')),
    path('store/', include('jijistore.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='jijiapp/registration/login.html', authentication_form=LoginForm), name='login'),
    # path('accounts/', include('django.contrib.auth.urls')),
    # path('inbox/', include('jijiapp.routing')),
    
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(
        template_name='jijiapp/registration/password_reset.html'), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='jijiapp/registration/password_reset_done.html'), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='jijiapp/registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='jijiapp/registration/password_reset_complete.html'), name='password_reset_complete'),

]
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

jijistore/urls.py
from django.urls import path
from jijistore import views
from jijiapp.views import edit_item

app_name = 'jijistore'

urlpatterns = [
    path('storelist/', views.storelist, name='storelist' ),
    path('all_store/', views.all_store, name='all_store' ),
    path('enter_store/<str:store>/', views.enter_store, name='enter_store'),
    path('edit_store/<int:store_id>/', views.edit_store, name='edit_store'),
    # path('edit_item/<int:items_id>/', edit_item, name='edit_item'),
]

jijiapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.core.mail import send_mail

# Create your models here.

class Category(models.Model):
    FOOD = 'Food'
    AGRICULTURE = 'Agriculture'
    COMPUTER = 'Computer'
    ELECTRONICS = 'Electronics'
    FASHION = 'Fashion'
    SCHOOL = 'School'
    TAILOR = 'Tailor'
    TOOL = 'Tools'
    PHONE = 'Phone'
    KITCHEN = 'Kitchen'
    RIDE = 'Ride'
    CARS = 'Car'
    OFFICE = 'Office'
    JEWELRY = 'Jewelry'
    
    CATEGORY_CHOICES = (
        (FOOD, 'Food'),
        (AGRICULTURE, 'Agriculture'),
        (COMPUTER, 'Computers'),
        (ELECTRONICS, 'Electronics'),
        (FASHION, 'Fashion'),
        (SCHOOL, 'School'),
        (TAILOR, 'Tailor'),
        (TOOL, 'Tools'),
        (PHONE, 'Phone'),
        (KITCHEN, 'Kitchen'),
        (RIDE, 'Ride'),
        (CARS, 'Cars'),
        (OFFICE, 'Office'),
        (JEWELRY, 'Jewelry'),
    )
    
    name = models.CharField(max_length=50, choices=CATEGORY_CHOICES)
    icon_class = models.CharField(max_length=50, null = True)
    
    def __str__(self):
        return self.name

class Store(models.Model):
    name = models.SlugField(unique =True, max_length=50)
    author = models.ForeignKey(User, on_delete=models.CASCADE, blank=False)
    create_date = models.DateTimeField(auto_now_add=True, null=True)
    discription=models.CharField(max_length=5000, null=True, blank=True)
    location =models.CharField(max_length=5000, null=True, blank=True)
    logo =models.ImageField(upload_to='logos/', default = '')
    category = models.ManyToManyField(Category, related_name ='cat')
    
    def __str__(self):
        return '%s' % (self.name)
    
    class Meta:
        ordering = ['-name']
        verbose_name_plural = 'Store'
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    content = models.CharField(max_length=300, null=True, blank =True)
    post_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    item=models.ForeignKey('Items', on_delete = models.CASCADE, null=True, blank = True)   

class UserItemView(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    view_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    item=models.ForeignKey('Items', on_delete = models.CASCADE, null=True, blank = True)
    
    def __str__(self):
        return self.item.title 
    class Meta:
        ordering = ['-view_date',] 
        
class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    item=models.ForeignKey('Items', on_delete = models.CASCADE, null=True, blank = True)
    
class Contact(models.Model):
    name = models.CharField(max_length=100, null=False)
    email = models.EmailField(max_length=50, null=False)
    message = models.CharField(max_length=100, null=False)
    contact_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    
    def __str__(self):
        return self.name
    class Meta:
        ordering =['-contact_date',]
        
class Rating(models.Model):
    item = models.ForeignKey('Items', on_delete=models.CASCADE, related_name='ratings')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)


class Items(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE, related_name='supplier')
    store = models.ForeignKey(Store, on_delete=models.CASCADE, null=True, blank = True)
    title = models.CharField(max_length=10, null=True, blank =True)
    description = models.CharField(max_length=1000, null=True, blank=True)
    price = models.CharField(max_length=20, null=True, blank=True)
    phone = models.CharField(max_length=20, null=True, blank=True)
    location =models.CharField(max_length=20, null=True, blank=True)
    post_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    thumbnails =models.ImageField(upload_to='thumbnails/', null=True, blank=True)
    category = models.ManyToManyField(Category, related_name ='categories')
    

    def __str__(self):
        return self.title

    class Meta:
        ordering =['-post_date',]
        verbose_name_plural ='Items'

class Images(models.Model):
    image =models.ImageField(upload_to='media/', null=True, blank=True)
    item=models.ForeignKey(Items, on_delete = models.CASCADE, null=True, blank = True)
   

    def __str__(self):
        return str(self.item.title)
    
    class Meta:
        verbose_name_plural ='Images'
    
class Conversation(models.Model):
    item = models.ForeignKey(Items, related_name='conversations', on_delete=models.CASCADE, null = True, blank = True)
    members = models.ManyToManyField(User, related_name='conversations')
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    

    def __str__(self):
        return self.item.title

    class Meta:
        ordering = ('-created_at',)
    
class ConversationMessage(models.Model):
    conversation = models.ForeignKey(Conversation, related_name='messages', on_delete=models.CASCADE, null = True, blank = True)
    content = models.TextField(max_length =1000, null = True, blank = True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name='created_messages', on_delete=models.CASCADE, null = True, blank = True)
    is_admin_reply =models.BooleanField(default = False)
     
    def __str__(self):
        return self.content
    
    class Meta:
        ordering = ('-created_at',)
class ConversationCount(models.Model):
    conversation = models.ForeignKey(Conversation, related_name='messages_count', on_delete=models.CASCADE, null = True, blank = True)   
    message_count = models.IntegerField(default=1)

# counting inbox
from django.core.exceptions import ObjectDoesNotExist

@receiver(post_save, sender=ConversationMessage)
@receiver(post_delete, sender=ConversationMessage)
def update_conversation_message_count(sender, instance, **kwargs):
    try:
        conversation = getattr(instance, 'conversation', None)
        
        if conversation is None:
            return  # Skip further processing if the conversation is not available
        
        conversation_count, created = ConversationCount.objects.get_or_create(conversation=conversation)
        conversation_count.message_count = conversation.messages.count()
        conversation_count.save()
    except ObjectDoesNotExist:
        pass


    
class Suppliers(models.Model):
    items = models.OneToOneField(Items, on_delete=models.CASCADE)
    post_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    
    class Meta:
        
        verbose_name_plural = 'Supplier'

class Counts(models.Model):
    image = models.ForeignKey(Images, on_delete = models.CASCADE, null=True, blank = True)
class HomeImage(models.Model):
    image = models.ImageField(upload_to = 'HomeImage')

# signal
@receiver(post_save, sender=ConversationMessage)
def send_notification_email(sender, instance, created, **kwargs):
    if created:
        conversation = instance.conversation
        if conversation and conversation.item:
            item_store = conversation.item
            user = instance.created_by

            # send email to supplier if message was created by customer
            if user != item_store.user:
                supplier_email = item_store.user.email
                subject = f'New message about {item_store.title}'
                message = f'You have a new message about {item_store.title} from {instance.created_by}.\n\n'
                message += f'Message Content: {instance.content}\n\n'
                message += f'Conversation: {instance.conversation}'
                from_email = 'mathiaswilfred7@yahoo.com'
                recipient_list = [supplier_email]
                send_mail(subject, message, from_email, recipient_list)

            # send email to customer if message was created by supplier
            elif user == item_store.user:
                for member in conversation.members.all():
                    if member != user:
                        customer_email = member.email
                        subject = f'New reply about {item_store.title}'
                        message = f'{item_store.user.username} replied to your message at Wilf Marke Place about {item_store.title}.\n\n'
                        message += f'Message Content: {instance.content}\n\n'
                        message += f'Conversation: {instance.conversation}'
                        from_email = 'mathiaswilfred7@yahoo.com'
                        recipient_list = [customer_email]
                        send_mail(subject, message, from_email, recipient_list)

jijiapp/forms.py
from django.forms import ModelForm
from .models import Items, Images
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.forms.widgets import ClearableFileInput
from multiupload.fields import MultiFileField, MultiMediaField
from django.contrib.auth.forms import AuthenticationForm



# from multiupload.widgets import MultiClearableFileInput


from .models import ConversationMessage, Category



class ConversationMessageForm(forms.ModelForm):
    class Meta:
        model = ConversationMessage
        fields = ('content',)
        widgets = {
            'content': forms.Textarea(attrs={
                'class': 'w-10 rounded-xl border'
            })
        }
        


# class CategoryModelMultipleChoiceField(ModelMultipleChoiceField):
#     def label_from_instance(self, obj):
#         return obj.name

# class ItemsForm(forms.ModelForm):
#     category = CategoryModelMultipleChoiceField(queryset=Category.objects.all(), widget=forms.CheckboxSelectMultiple)

#     class Meta:
#         model = Items
#         exclude = ['user', 'store']


class ItemsForm(ModelForm):
    
    category = forms.ModelMultipleChoiceField(queryset=Category.objects.all(),
                                      widget=forms.SelectMultiple,)


    class Meta:
        model =Items
        # fields = ['title', 'price', 'phone', 'location','description', 'thumbnails', 'category']
        exclude = ['user', 'store']
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categorys =[(cat.id, cat.name) for cat in Category.objects.all()] 
        self.fields['category'].choices = [('', 'Select a Category')] + categorys   

class ImageForm(forms.ModelForm):
    image = MultiFileField(max_num=5, min_num=1)

    class Meta:
        model = Images
        fields = ['image',]

# class ImageForm(forms.ModelForm):
#     image = MultiFileField(widget=MultiClearableFileInput(attrs={'class': 'form-control'}))

#     class Meta:
#         model = Images
#         fields = ['image',]


# class ImageForm(ModelForm):
#     image = forms.ImageField(widget=ClearableFileInput(attrs={'class': 'form-control', "multiple":True}))

#     class Meta:
#         model = Images
#         fields = ['image',]
  
# class ImageForm(ModelForm):
#     image = forms.ImageField(widget =forms.FileInput(attrs  = {'class':'form-control',
#                 "multiple":True}))
    
#     class Meta:
#         model =Images
#         fields = ['image',]
        
# authentication

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': ''
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': ''
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': ''
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': ''
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': ''
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': ''
    }))
    
        
class CommentForm(forms.Form):
    detail = forms.CharField(label='Enter you View')
    
    

jijiapp/templates/jijiapp/confirm_delete.html
{% extends 'jijiapp/base/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Upload Item {% endblock %}


{% block content %}
<div class="container mb-3" style="font:bold;">
    <div class="col-5 bg-dark mx-auto text-white">
        <div class="text-center pt-5 pb-3 mx-3">
            <p class="lead text-bold" style="font-size:2rem; font-weight: bold;">Are you sure you want to delete the store "{{ store.name }}"?</p>
            <small class="text-danger">if you delete {{ store.name}}, You will loose all items you added inside</small>
        </div>
        <hr>
        <div class="row mx-auto mx-5">
            <div class="col-5 mx-3 px-3 mb-3 mx-auto">
                <form method="post" action="{{ delete_url }}">
                    {% csrf_token %}
                    <button class="btn btn-success bg-success" name="confirm_delete">Yes, delete</button>
                    
                </form>
            </div> 
            <div class="col-5 mx-3 px-3 mb-3">
                <a href="{% url 'jijistore:all_store' %}" class="btn btn-success bg-success">No, cancel</a>
            
            </div>   
                
        </div>

    </div>
    
</div>

{% endblock %}

jijiapp/templates/jijiapp/confirm_delete_item.html
{% extends 'jijiapp/base/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Upload Item {% endblock %}


{% block content %}
<div class="container mb-3" style="font:bold;">
    <div class="col-5 bg-dark mx-auto text-white">
        <div class="text-center pt-5 pb-3 mx-3">
            <p class="lead text-bold" style="font-size:2rem; font-weight: bold;">Are you sure you want to delete "{{ item.title }}"?</p>
            <small class="text-danger">if you delete {{ item.title }}, it will be deleted permanently!</small>
        </div>
        <hr>
        <div class="row mx-auto mx-5">
            <div class="col-5 mx-3 px-3 mb-3 mx-auto">
                <form method="post" action="{{ delete_url }}">
                    {% csrf_token %}
                    <button class="btn btn-success bg-success" name="confirm_delete">Yes, delete</button>
                    
                </form>
            </div> 
            <div class="col-5 mx-3 px-3 mb-3">
                <a href="{% url 'jijistore:all_store' %}" class="btn btn-success bg-success">No, cancel</a>
            
            </div>   
                
        </div>

    </div>
    
</div>

{% endblock %}

jijiapp/templates/jijiapp/jijidetail.html
{% extends 'jijiapp/base/base.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block content %}


  <!-- images -->
  
   <div class="card bg-light mb-3">
    <div class="card-header text-center mb-5">
      <h5>Product Images</h5>
    </div>
    <div class="card-body d-flex flex-nowrap overflow-auto" style="max-width: 100%; overflow-x: auto;">
      {% for img in detail_item.images_set.all %}
      <div class="col-sm-4 col-md-4 col-lg-3 thumbnail mb-3 img-zoom">
        <div class="card">
          <img src="{{ img.image.url }}" alt="Product Image" class="card-img-top img-thumbnails img-fluid" style="height: 300px; width: auto; object-fit: contain;">
          <div class="card-footer text-center">
            <small class="text-muted">{{ img.name }}</small>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
      
  
  
  <!-- end of images -->

<div class="container mx-5 pt-5 maindetailss" style="padding-bottom: 50px; justify-content: center; ">
  <div class="row mb-3">
    <div class="row">
      <div class="col-md-3 col-sm-12 col-lg-3 col-sm-4 mx-auto pt-3">
        <img src="{{ detail_item.thumbnails.url }}" alt="first image" class="col-md-4 col-sm-12 img-thumbnails img-zoom" style="width: 300px; height: auto;">      
      </div>
        <div class="col-md-9 col-sm-12">
          <p class="pt-3 bg-dark text-center" style="font-size: 1.5rem; font-weight: bold; color:white; font-family: 'Montserrat', sans-serif;">{{ detail_item.description }}</p>
          <hr>
          <p class="lead" style="font-size: 1.5rem; color: #546e7a; font-family: 'Open Sans', sans-serif;">Price: <strike>N</strike>{{ detail_item.price }}</p>
          <hr>
         
          <button class="btn num" id="num" onclick="myFunction()" style="font-size: 1rem; font-family: 'Montserrat', sans-serif; background-color: #ffb900; border-color: #ffb900;">Show Contact</button>
          
          <hr>
          {% if user != detail_item.user %}
          <a href="{{ chat_url }}" class="btn btn-secondary num" style="font-size: 1.5rem; font-family: 'Montserrat', sans-serif; background-color: #546e7a; border-color: #546e7a;">Chat with {{ detail_item.user }}! You can negotiate the price</a><hr>
          <span class="lead" style="font-size: 1rem; color: #546e7a; font-family: 'Open Sans', sans-serif;">Supplier: {{ detail_item.user }}</span>
          {% else %}
          <hr><a href="{% url 'jijistore:all_store' %}" class="btn btn-secondary num" style="font-size: 1.5rem; font-family: 'Montserrat', sans-serif; background-color: #546e7a; border-color: #546e7a;">Go to store</a>
          {% endif %}
          
          <hr>
          <span class="lead" style="font-size: 1rem; color: #546e7a; font-family: 'Open Sans', sans-serif;">Posted since: {{ detail_item.post_date |date  }}</span>
          <hr>
          <a class="lead btn btn-success mb-4" href="{{ store_routing }}" style="font-size: 1.5rem; font-family: 'Montserrat', sans-serif; background-color: #1a237e; border-color: #1a237e;">This "{{ detail_item.title }}" is coming from "{{ detail_item.store.name }}" store! View all items in this store <b>Enter store</b></a>
        
      
      
            <!-- rating -->
            <form method="post"id="rating-form" action=".">
              {% csrf_token %}
              <div class="form-group">
                  <label for="rating">Rate this item:</label>
                  <div class="star-rating">
                      <input type="radio" id="star5" name="rating" value="5" style="display:none;">
                      <label for="star5" title="5 stars" style="cursor:pointer;">
                          <i class="fa fa-star" style="font-size:24px; color:#FFD700;"></i>
                      </label>
                      <input type="radio" id="star4" name="rating" value="4" style="display:none;">
                      <label for="star4" title="4 stars" style="cursor:pointer;">
                          <i class="fa fa-star" style="font-size:24px; color:#FFD700;"></i>
                      </label>
                      <input type="radio" id="star3" name="rating" value="3" style="display:none;">
                      <label for="star3" title="3 stars" style="cursor:pointer;">
                          <i class="fa fa-star" style="font-size:24px; color:#FFD700;"></i>
                      </label>
                      <input type="radio" id="star2" name="rating" value="2" style="display:none;">
                      <label for="star2" title="2 stars" style="cursor:pointer;">
                          <i class="fa fa-star" style="font-size:24px; color:#FFD700;"></i>
                      </label>
                      <input type="radio" id="star1" name="rating" value="1" style="display:none;">
                      <label for="star1" title="1 star" style="cursor:pointer;">
                          <i class="fa fa-star" style="font-size:24px; color:#FFD700;"></i>
                      </label>
                  </div>
                  <div class="rating-text" style="font-size:16px; font-weight:bold; margin-top:10px;"></div>
              </div>
              <button type="submit" class="btn btn-primary" style="background-color:#4CAF50; border:none; padding:10px 20px; color:white; font-size:16px; cursor:pointer;">Submit</button>
              
                  <div class="" style="margin-top:10px;">
                    {% for m in messages %}
                    <strong class="alert alert-danger" style="padding:10px;">{{ m }}</strong> 
                    {% endfor %}
                  </div>
              
          </form>
      </div>  
        
    </div>  
  </div>

</div>
      
<div class="pt-3 col-md-12 col-sm-12 mx-auto mb-5">
  <div class="mx-auto" style="border: 2px solid red; max-width: 300px; padding: 20px; border-radius: 10px;">
    <div class="" style="justify-content: center; text-align: center;">
      <h1 class="" style="color: red; font-size: 2rem;"><i class="fa fa-exclamation-triangle"></i><br><span style="font-weight: bold; text-decoration: underline;">Caution</span></h1>
      <p class="lead" style="font-size: 1rem; line-height: 1.5; color: #444;">This person you are buying this stuff from may be a complete stranger and it is encouraged that you should be vigilant. Never pay money without receiving the item.</p>
    </div>
  </div>
</div>
      
<!-- converstaion started -->

<div class="container-fluid bg-dark py-5 mb-5">
  <h1 class="text-center text-white mb-6">Feedbacks</h1>
  <div class="container">
    <div class="col-md-5 col-sm-12 mx-auto">
      <form method="post" id ="feedback-form" class="mt-6 js">
        {% csrf_token %}
        {{ form.detail | as_crispy_field }}
        <button class="btn btn-primary">Send</button>
      </form>
      
      <div id="feedbacks-container"></div>
      <div class="comments-container">
        {% for comment in comments|slice:":3" %}
        <div class="p-3 my-4" style="background-color: rgba(255,255,255,0.9);">
          <div class="shadow shadow-dark mx-auto p-3 pt-2 lead">
            <p>{{ comment.content }}</p>
            <small class="text-muted">{{ comment.user }} | {{ comment.post_date }}</small>
          </div>
        </div>
        {% endfor %}
      
        {% if comments.count > 3 %}
        <a href="#" id="toggle-button" class="toggle-button text-white">Show all feedbacks</a>
        {% endif %}
      </div>
      
      <div class="hidden-comments" id="hidden-comments" style="display: none;">
        {% for comment in comments|slice:"4:" %}
        <div class="p-3 my-4" style="background-color: rgba(255,255,255,0.9);">
          <div class="shadow shadow-dark mx-auto p-3 pt-2 lead">
            <p>{{ comment.content }}</p>
            <small class="text-muted">{{ comment.user }} | {{ comment.post_date }}</small>
          </div>
        </div>
        {% endfor %}
      </div>
      
    </div>
  </div>
</div>
 <!-- category -->

<div class="container container-fluid mb-5">
  <div class="row pt-5 bg-dark rowheight">
    {% for cat in category %}
    <div class="col-lg-4 col-md-4 col-sm-6 mb-5 colheight">
      <div class="card bg-light card-style">
        <a href="{% url 'detail' cat.id %}" class="card-link text-decoration-none">
          <img src="{{ cat.thumbnails.url }}" alt="First Image" class="card-img-top img-fluid mx-auto align-items-stretch">
        </a>
        <div class="card-body">
          <h5 class="card-title">{{ cat.title }}</h5>
          <hr class="star-light">
          <p class="card-text">Price: <strike>N</strike>{{ cat.price }}</p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

<!-- end -->

{% include 'jijiapp/base/footer.html' %}
{% block scripts %}
<script>
  
  $(document).ready(function() {
      function myFunction() {
          var phone = document.getElementById("num");
          phone.textContent = "{{ detail_item.phone }}";
          console.log(num);
      }

      $('#num').click(function() {
          myFunction();
      });

      $('.star-rating label').hover(function() {
          $(this).prevAll().addBack().addClass('hover');
          $(this).nextAll().removeClass('hover');
          var rating = $(this).attr('title');
          $('.rating-text').text(rating);
      }, function() {
          $(this).prevAll().addBack().removeClass('hover');
          $('.rating-text').text('');
      });

      $('.star-rating input').change(function() {
          var rating = $(this).siblings('label').attr('title');
          $('.rating-text').text('You rated this ' + rating);
      });

  // show and hide feedback
  
  $("#toggle-button").click(function(e) {
    e.preventDefault();
    $("#hidden-comments").toggle();
    if ($("#hidden-comments").is(":visible")) {
      $(this).text("Hide feedbacks");
    } else {
      $(this).text("Show all feedbacks");
    }
  });

  //stop form from reloading
  $("").click(function(e) {
    e.preventDefault();
    
  });

});

</script>
{% endblock %}
{% endblock %}

jijiapp/templates/jijiapp/view_all_users.html
{% extends 'jijiapp/base/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Upload Item {% endblock %}


{% block content %}

<div class="mx-5 px-5 col-md-5 mx-auto bg-info ">
    <div class = "row mb-3">
        <label class="col-md-2 col-form-label"></label>
        <div class="col-sm-10 form-control">
            <a href="{% url 'list_of_user' %}">List of all customers</a>
        </div>
        
    </div> 
    
{% endblock %}